In [1]:
import pandas as pd

In [2]:
path = '/Users/zhuangyuhao/PycharmProjects/SeasonRepMod/'

In [3]:
df18 = pd.read_excel(path + '整合季报代码模型/整合后台数据/开发库/df18.xlsx')
df19 = pd.read_excel(path + '整合季报代码模型/整合后台数据/开发库/df19.xlsx')
df20 = pd.read_excel(path + '整合季报代码模型/整合后台数据/开发库/df20.xlsx')
df21 = pd.read_excel(path + '整合季报代码模型/整合后台数据/开发库/df21.xlsx')
df22 = pd.read_excel(path + '整合季报代码模型/整合后台数据/开发库/df22.xlsx')

In [7]:
df_total = pd.concat([df18, df19, df20, df21, df22])
df_total.drop(columns="Unnamed: 0", inplace=True)

In [5]:
# df_total.to_excel(path + '整合季报代码模型/整合后台数据/开发库/df_202122.xlsx')

In [8]:
df_total

,BASIC_entity_name,BASIC_code,BASIC_industry,BASIC_year,BASIC_quarter,Unnamed: 6,QW_ACCOUNTSRECEIVABLETURNOVER,QW_ACCOUNTSRECEIVABLETURNOVER_DELTA,QW_ACCOUNTSRECEIVABLETURNOVER_DELTA_2,QW_ACCOUNTSRECEIVABLETURNOVER_GROWTH,...,QW_SELLEXPENSE_RATIO_DELTA,QW_SHORTBORROWING_RATIO,QW_SHORTBORROWING_RATIO_DELTA,QW_STOCK_RATIO,QW_STOCK_RATIO_DELTA,QW_TOTALASSETTURNOVER,QW_TOTALASSETTURNOVER_DELTA,QW_TOTALASSETTURNOVER_DELTA_2,QW_TOTALASSETTURNOVER_GROWTH,QW_TOTALASSETTURNOVER_GROWTH_2
0,1957 & Co.(Hospitality) Limited,8495.HK,M002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,360鲁大师控股有限公司,3601.HK,M014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,361度国际有限公司,1361.HK,M007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A8新媒体集团有限公司,0800.HK,M014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ASMPT Limited,0522.HK,M014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18872,龙芯中科技术股份有限公司,688047.SH,M001,2022.0,2.0,NaN,-999999.999900,-999999.9999,-999999.9999,-999999.9999,...,-999999.999900,-999999.9999,-999999.9999,0.129420,-999999.999900,-999999.99990,-999999.9999,-999999.9999,-999999.9999,-999999.9999
18873,龙芯中科技术股份有限公司,688047.SH,M001,2022.0,3.0,NaN,0.867566,-999999.9999,-999999.9999,-999999.9999,...,0.016137,-999999.9999,-999999.9999,0.143554,0.014134,0.10977,-999999.9999,-999999.9999,-999999.9999,-999999.9999
18874,龙记(百慕达)集团有限公司,0255.HK,M008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18875,龙资源有限公司,1712.HK,M003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18876,龙辉国际控股有限公司,1007.HK,M002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_total[df_total.BASIC_entity_name == '协鑫智慧能源(苏州)有限公司']

,BASIC_entity_name,BASIC_code,BASIC_industry,BASIC_year,BASIC_quarter,Unnamed: 6,QW_ACCOUNTSRECEIVABLETURNOVER,QW_ACCOUNTSRECEIVABLETURNOVER_DELTA,QW_ACCOUNTSRECEIVABLETURNOVER_DELTA_2,QW_ACCOUNTSRECEIVABLETURNOVER_GROWTH,...,QW_SELLEXPENSE_RATIO_DELTA,QW_SHORTBORROWING_RATIO,QW_SHORTBORROWING_RATIO_DELTA,QW_STOCK_RATIO,QW_STOCK_RATIO_DELTA,QW_TOTALASSETTURNOVER,QW_TOTALASSETTURNOVER_DELTA,QW_TOTALASSETTURNOVER_DELTA_2,QW_TOTALASSETTURNOVER_GROWTH,QW_TOTALASSETTURNOVER_GROWTH_2
6160,协鑫智慧能源(苏州)有限公司,NaN,M004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6161,协鑫智慧能源(苏州)有限公司,112624.SZ,M004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6160,协鑫智慧能源(苏州)有限公司,NaN,M004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6161,协鑫智慧能源(苏州)有限公司,112624.SZ,M004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6160,协鑫智慧能源(苏州)有限公司,NaN,M004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6161,协鑫智慧能源(苏州)有限公司,112624.SZ,M004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5013,协鑫智慧能源(苏州)有限公司,NaN,M004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5014,协鑫智慧能源(苏州)有限公司,112624.SZ,M004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5048,协鑫智慧能源(苏州)有限公司,NaN,M004,2022.0,1.0,NaN,-999999.9999,-999999.9999,-999999.9999,-999999.9999,...,-999999.9999,-999999.999900,-999999.9999,-999999.999900,-999999.9999,-999999.9999,-999999.9999,-999999.9999,-999999.9999,-999999.9999
5049,协鑫智慧能源(苏州)有限公司,NaN,M004,2022.0,2.0,NaN,-999999.9999,-999999.9999,-999999.9999,-999999.9999,...,-999999.9999,0.081536,-999999.9999,0.010106,-999999.9999,-999999.9999,-999999.9999,-999999.9999,-999999.9999,-999999.9999
5050,协鑫智慧能源(苏州)有限公司,112624.SZ,M004,2022.0,1.0,NaN,-999999.9999,-999999.9999,-999999.9999,-999999.9999,...,-999999.9999,-999999.999900,-999999.9999,-999999.999900,-999999.9999,-999999.9999,-999999.9999,-999999.9999,-999999.9999,-999999.9999
5051,协鑫智慧能源(苏州)有限公司,112624.SZ,M004,2022.0,2.0,NaN,-999999.9999,-999999.9999,-999999.9999,-999999.9999,...,-999999.9999,0.081536,-999999.9999,0.010106,-999999.9999,-999999.9999,-999999.9999,-999999.9999,-999999.9999,-999999.9999